/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ciux031701_kandidat360degrees_representation_NativePanorama */

#ifndef _Included_com_ciux031701_kandidat360degrees_representation_NativePanorama
#define _Included_com_ciux031701_kandidat360degrees_representation_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ciux031701_kandidat360degrees_representation_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ)V
 */
JNIEXPORT jobject JNICALL Java_com_ciux031701_kandidat360degrees_representation_NativePanorama_processPanoramaFromHandles(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
